common:
    exp_name: e2e_exp001
    train_data: chinese_ocr_dataset/images
    valid_data: chinese_ocr_dataset/images
    train_label: chinese_ocr_dataset/data_train.txt
    valid_label: chinese_ocr_dataset/data_test.txt
    num_iter: 300000
    valInterval: 2000
    continue_model: False
    reco_lr: 0.5
    lr: 3.2768e-5
    num_epoch: 1000
    print_freq: 10
    batch_size: 8
    eval_iter: 2000
    target_size: 768

    adam: False
    reco_beta1: 0.9
    rho: 0.95
    eps: 0.00000001
    grad_clip: 5


    select_data: MJ-ST
    batch_ratio: 0.5-0.5
    total_data_usage_ratio: 1.0
    batch_max_length: 40
    imgH: 32
    imgW: 100
    rgb: False
    character: 0123456789abcdefghijklmnopqrstuvwxyz 
    sensitive:  
    PAD: 
    data_filtering_off: 


    Transformation: TPS
    FeatureExtraction: VGG
    SequenceModeling: BiLSTM
    Prediction: Attn
    num_fiducial: 20
    input_channel: 1
    output_channel: 512
    hidden_size: 256
