common:
    exp_name: rcnn_exp001
    train_data: data/data_lmdb_release/training
    valid_data: data/data_lmdb_release/validation
    workers: 4
    batch_size: 192
    num_iter: 300000
    valInterval: 2000
    continue_model: False
    lr: 1
    adam: False
    beta1: 0.9
    rho: 0.95
    eps: 0.00000001
    grad_clip: 5


    select_data: MJ-ST
    batch_ratio: 0.5-0.5
    total_data_usage_ratio: 1.0
    batch_max_length: 25
    imgH: 32
    imgW: 100
    rgb: False
    character: 0123456789abcdefghijklmnopqrstuvwxyz 
    sensitive:  
    PAD: 
    data_filtering_off: 


    Transformation: None
    FeatureExtraction: VGG
    SequenceModeling: BiLSTM
    Prediction: CTC
    num_fiducial: 20
    input_channel: 1
    output_channel: 512
    hidden_size: 256
